### ISSUE TITLE
Invalid JSON crashes contexter

### ISSUE THREAD

**Issue by billiegoose** [elingerojo/contexter#2]
I tried to create a new file to see contexter-cli update magically,

```
touch ANOTHER_THING.json
```

and it crashed.
```
SyntaxError: E:\git\BetterCode\create-node-module\ANOTHER_THING.json: Unexpected end of JSON input
```

The good news is I know exactly why:
```js
    if (isJSON()) {
      // if not the first time, delete cache
      if (file.data) delete require.cache[require.resolve(file.path.full)]
      data = require(file.path.full)
    }
```

Internally I think Node uses `JSON.parse` to `require()` JSON files, and `JSON.parse` throws an exception if it fails. I would suggest using plain old `JSON.parse` (so you don't have to deal with the `require.cache`) and adding some error handling like so:

```js
try {
    if (isJSON()) {
      data = JSON.parse(file.path.full)
    } else if (isYML()) {
      data = yaml.safeLoad(fs.readFileSync(file.path.full, 'utf8'))
    }
} catch (err) {
    return callback(err)
}
return callback(null, data)
```

Sorry I'm too lazy to make a pull request. I didn't start writing this issue with the intent of presenting a solution... just got carried away...

**Comment by elingerojo** [comment]
Ok
I will do it, right away.
Thanks

**Comment by elingerojo** [comment]
You are right.
`require()` uses plain `JSON.parse()` ([see source](https://github.com/nodejs/node/blob/75487f0db80e70a3e27fabfe323a33258dfbbea8/lib/module.js#L546-L554))

The `default-datafile-plugin.js` uses `jus` code. So this particular `require` solution comes from it 

(I am trying to keep as much `jus` code in `contexter` as possible so it can be easily included in future `jus` versions)

I think that the original logic was to read JSON file once and [cache the following reads](http://stackoverflow.com/questions/35389060/read-json-file-content-with-require-vs-fs-readfile) but ...
...later this was an [issue about not refreshing](https://github.com/jus/jus/issues/17) so I fixed it in `jus` with the ` delete require.cache`

So, we have come the hole circle back... to better use plain `JSON.parse()` ...ha ha ha 😂 

To remove the `require()` solution, I think, I will have to change or remove some test

**Comment by elingerojo** [comment]
This code:
```js
try {
    if (isJSON()) {
      data = JSON.parse(file.path.full)
    } else if (isYML()) {
      data = yaml.safeLoad(fs.readFileSync(file.path.full, 'utf8'))
    }
} catch (err) {
    return callback(err)
}
return callback(null, data)
```

Throws the error upstream in the caller so not much gained 😞 

---

What do you think of the following solution?

```js
    try {
        if (isJSON()) data = JSON.parse(fs.readFileSync(file.path.full, 'utf8'))
        if (isYML()) data = yaml.safeLoad(fs.readFileSync(file.path.full, 'utf8'))
    } catch (err) {
      // Only syntax error can be handled
      if (!(err instanceof SyntaxError)) return callback(err)
      // Let the user know the reason that `file.data` will be empty object
      console.log(
`
${err} inside file: ${file.path.relative}

Consider correcting it so parsed data will not be an empty object
...['${file.path.relative}'].data = {}
`
      )
      data = {}
    }

    return callback(null, data)
```

For user input syntax error, will not throw errors and will show this:


```
Started contexting dir...

SyntaxError: Unexpected end of JSON input inside file: /ANOTHER_THING.json

Consider correcting it so parsed data will not be an empty object
...['/ANOTHER_THING.json'].data = {}

  /ANOTHER_THING.json added
  /assets/photo.jpg added
  /assets/posts.yml added
.done!
The server now is running at http://localhost:3000
```

My concern will be that an "opinionated" solution for a library may not be good from the programmer perspective

Any thoughts?

**Comment by billiegoose** [comment]
I think that `contexter` should pass up any errors it encounters, so that `contexter-cli` or `wills-live-hotreloading-compiler` can choose how to present them. Though I'm not sure how error reporting in contexter works, I imagine it would be something like linter errors? E.g. each file could have an array of errors you could attach to it.

**Comment by billiegoose** [comment]
> You are right.
> require() uses plain JSON.parse() (see source)

I'm impressed that you located the actual source code! :)

**Comment by elingerojo** [comment]
Summary (tl; dr;)

- `contexter` throws it
- `contexter-cli` handles it (...maybe by a message and default to empty object)

---

> I'm not sure how error reporting in contexter works

At present, there is non at all. Maybe it is a good time to start thinking of it 😀 

I will start with this SyntaxError

From [Error Handling in Node.js](https://www.joyent.com/node-js/production/design/errors)  
> The next most common case is an operational error in a synchronous function like JSON.parse. For these functions, if you encounter an operational error (like invalid user input), you have to deliver the error synchronously. You can either throw it (much more common) or return it.

...it goes on and basically says what you already told me 😀 

>I think that contexter should pass up any errors it encounters

**Comment by billiegoose** [comment]
> At present, there is non at all. Maybe it is a good time to start thinking of it

It's never too early to think about errors! My philosophy is that debugging takes up 50-90% of your time as a developer. Well designed error messages / error handling systems can greatly decrease that time, or at least make for a more pleasant developer experience. Just search for "elm error" on Twitter - you'll be amazed.

I'm actually a huge fan of error messages and am working on creating a forum/wiki for all the errors in the world, because I think the #1 thing that could help improve the quality of software in the world is breaking down the taboo about discussing errors. Errors are not a bad thing! They should be embraced. Try/catch should be as popular as if/else.

Which makes me wonder, does JSON.parse actually report the line/column? If not, let's find a JSON parsing library that provides a more useful description.

**Comment by elingerojo** [comment]
> Just search for "elm error"

Wow!
It's a big world out there. I wasn't aware of the it

I will place more effort on error handling from now on. I just had a good time coding the error handling for **contexter-cli** as it got more interesting

By the way, bumped **contexter** to 1.0.1
Changed to plain JSON.parse() and error handling to caller

So... also bumped **contexter-cli** to 0.5.0
Add parse error handling

You may like the "red message" handling in browser for "bad" (unparsed) files

**Comment by elingerojo** [comment]
**Invalid JSON crashes contexter** 

Fixed by [this commit](https://github.com/elingerojo/contexter/commit/cfc57a10eb9b052b0ccc9a46d7579c2485fae840)

**Comment by billiegoose** [comment]
> You may like the "red message" handling in browser for "bad" (unparsed) files

I think "like" is an understatement! You made the error indicator bubble up the tree! 😍 

![image](https://cloud.githubusercontent.com/assets/587740/26204676/70fa5fe0-3bad-11e7-96e8-19954f970f8b.png)

![image](https://cloud.githubusercontent.com/assets/587740/26204703/891615f6-3bad-11e7-9215-dc0d8e0da0fb.png)

![image](https://cloud.githubusercontent.com/assets/587740/26204831/0169aad6-3bae-11e7-9b37-f65d80e34a64.png)

**I like how that leads me straight to the error like a trail of breadcrumbs!** Much more intuitive than /rant printing a list of errors at the bottom of the page like... well, C compilers \*cough\*. I've been writing some C code and using "gcc" a lot lately, and you make *one* tiny mistake and that thing prints a whole screen full of nonsense. "You forgot a comma" becomes "invalid implicit cast from const *char to void * and 5 more errors". /endrant

**Comment by elingerojo** [comment]
I am glad you like it.
